### PR TITLE
Russian Localization for OpenCms 10.0.1 initial import

### PR DESCRIPTION
**Pull request by makarov-iliya**
Russian Localization for OpenCms 10.0.1 core module initial import

### CODE REVIEW

**Comment by babinslava** [comment]
It would be good update, because now Russian locale is not very good.

**Comment by babinslava** [comment]
I tried this update, but still have issues with Russian letters in some places 
localization problems

@makarov-iliya do you know how to fix that issue?

**Comment by makarov-iliya** [comment]
The solution is here #406

**Comment by dSeidel** [comment]
Hi babinslava, I cherry-picked your commit for branch_10_0_x (already on GitHub) and branch_10_5_x (on GitHub soon). Thanks for your work!

**Pull request closed without merging**
