### PR TITLE
Chinese workplace localization

### PR DESCRIPTION
**Pull request by twofisher**

### CODE REVIEW

**Comment by dSeidel** [comment]
Hi @twofisher , it seems you are still working on the localization. Can you tell us when you finished it? Then we would like to include it in OpenCms 10.5. I'd like to merge latest at Nov. 23.
Thanks for your effort!

**Comment by twofisher** [comment]
Hi @dSeidel,  no problem,just update some less accurate translation。

**Comment by dSeidel** [comment]
Hi twofisher,
thanks for the translation! Actually I can't read it, but I think it's a great work to translate all those messages! I cleaned up a bit and fused all your commits in just two - one for the translation module and one for the tinymce codemirror plugin translations. The commits will be part of OpenCms 10.5.

It was some work to clean up, so I'd like to give you some advice for future pull requests:
- Please push only commits that contain a working (and cleaned up) extensions/fixes. You can commit locally in your repository as often as you want - but use "interactive rebase" to re-arrange your commits before pushing.
- Not everything that ends with .properties is part of the translation. Only bundles named messages.properties, clientmessages.properties or workplace.properties should be translated (with one or two exceptions). See the German localization for what should be translated. It is maintained by Alkacon and usually close to a complete translation - at least for the parts that should be translated. There are some bundles that are not translated by purpose. These are those with only log-messages inside that are printed to logs, not seen in the GUI. We noticed that support gets difficult if these are translated. What you should never translate are the query.properties, version.properties and some more files. The reason is, that, for example, query.property files are used for, you could say, "localization for databases" instead of "localization for languages".

Please take the above hints as suggestions on how you can improve.

I noticed very few untranslated parts, if you like to translate these as well, please wait till we push a more recent version of OpenCms on GitHub branch and open another pull request. The missing translations are:
- org/opencms/editors/sitemap/...
- org/opencms/search/replace/...
- org/opencms/ui/editors/...
- org/opencms/frontend/... (which is very unimportant to translate)

Best, and again many thanks, Daniel.

**Comment by twofisher** [comment]
hi @dSeidel,thank you for good  advice,this is my first time to use git,I will do more better next time.The missing translations will be commit  tomorrow.

**Pull request closed without merging**
